<?php

if (!function_exists('dental_care_dentalicons_array')) {


        function dental_care_dentalicons_array() {

        $dental_icons = array(
          "dental1-anesthesia",
          "dental1-braces",
          "dental1-brush-teeth",
          "dental1-caries-defence",
          "dental1-certificate",
          "dental1-cleaned-tooth",
          "dental1-cracked-tooth",
          "dental1-dental-caries",
          "dental1-dental-care",
          "dental1-dental-calculus",
          "dental1-dentist",
          "dental1-dentist-report",
          "dental1-healthy-tooth",
          "dental1-label",
          "dental1-medical-report",
          "dental1-medical-records",
          "dental1-parodontosis",
          "dental1-parodontosis-a",
          "dental1-pin-tooth",
          "dental1-patient-card",
          "dental1-protection",
          "dental1-teeth",
          "dental1-tooth-seal",
          "dental1-toothbrush",
          "dental1-x-ray"

        );

        return apply_filters('dental_care_dentalicons_array', $dental_icons);
    }

}

if (!function_exists('dental_care_dental2icons_array')) {


        function dental_care_dental2icons_array() {

        $dental_icons_two = array(
          "dental2-stethoscope",
          "dental2-tooth-11",
          "dental2-tooth-12",
          "dental2-x-ray",
          "dental2-tooth-13",
          "dental2-dental-floss-1",
          "dental2-certified",
          "dental2-smiling",
          "dental2-mobile-phone",
          "dental2-call-center",
          "dental2-tooth-14",
          "dental2-placeholder",
          "dental2-tooth-15",
          "dental2-tooth-16",
          "dental2-dentist-chair",
          "dental2-search",
          "dental2-mobile-phone-1",
          "dental2-tooth-17",
          "dental2-tooth-18",
          "dental2-tooth-19",
          "dental2-tooth-20",
          "dental2-insurance",
          "dental2-dental-care",
          "dental2-tooth-21",
          "dental2-placeholder-1",
          "dental2-tooth-22",
          "dental2-dentist-1",
          "dental2-toothbrush-1",
          "dental2-tooth-pliers-1",
          "dental2-implant",
          "dental2-tooth",
          "dental2-tooth-1",
          "dental2-toothbrush",
          "dental2-tooth-2",
          "dental2-tooth-3",
          "dental2-tooth-4",
          "dental2-dentist",
          "dental2-brace",
          "dental2-tooth-5",
          "dental2-tooth-6",
          "dental2-tooth-7",
          "dental2-mirror",
          "dental2-dental-drill",
          "dental2-syringe",
          "dental2-tooth-pliers",
          "dental2-mouthwash",
          "dental2-tooth-8",
          "dental2-dental-floss",
          "dental2-tooth-9",
          "dental2-tooth-10"
        );

        return apply_filters('dental_care_dental2icons_array', $dental_icons_two);
    }

}


if (!function_exists('dental_care_fontawesomeicons_array')) {


        function dental_care_fontawesomeicons_array() {

        $awesome_icons = array(
          "fa fa-500px",
          "fa fa-adjust",
          "fa fa-adn",
          "fa fa-align-center",
          "fa fa-align-justify",
          "fa fa-align-left",
          "fa fa-align-right",
          "fa fa-amazon",
          "fa fa-ambulance",
          "fa fa-american-sign-language-interpreting",
          "fa fa-anchor",
          "fa fa-android",
          "fa fa-angellist",
          "fa fa-angle-double-down",
          "fa fa-angle-double-left",
          "fa fa-angle-double-right",
          "fa fa-angle-double-up ",
          "fa fa-angle-down",
          "fa fa-angle-left",
          "fa fa-angle-right",
          "fa fa-angle-up",
          "fa fa-apple",
          "fa fa-archive",
          "fa fa-area-chart",
          "fa fa-arrow-circle-down",
          "fa fa-arrow-circle-left",
          "fa fa-arrow-circle-o-down",
          "fa fa-arrow-circle-o-left",
          "fa fa-arrow-circle-o-right",
          "fa fa-arrow-circle-o-up",
          "fa fa-arrow-circle-right",
          "fa fa-arrow-circle-up",
          "fa fa-arrow-down",
          "fa fa-arrow-left",
          "fa fa-arrow-right",
          "fa fa-arrow-up",
          "fa fa-arrows",
          "fa fa-arrows-alt",
          "fa fa-arrows-h",
          "fa fa-arrows-v",
          "fa fa-asl-interpreting",
          "fa fa-assistive-listening-systems",
          "fa fa-asterisk",
          "fa fa-at",
          "fa fa-automobile",
          "fa fa-backward",
          "fa fa-balance-scale",
          "fa fa-ban",
          "fa fa-bank",
          "fa fa-bar-chart",
          "fa fa-bar-chart-o",
          "fa fa-barcode",
          "fa fa-bars",
          "fa fa-battery-0",
          "fa fa-battery-1",
          "fa fa-battery-2",
          "fa fa-battery-3",
          "fa fa-battery-4",
          "fa fa-battery-empty",
          "fa fa-battery-full",
          "fa fa-battery-half",
          "fa fa-battery-quarter",
          "fa fa-battery-three-quarters",
          "fa fa-bed",
          "fa fa-beer",
          "fa fa-behance",
          "fa fa-behance-square",
          "fa fa-bell",
          "fa fa-bell-o",
          "fa fa-bell-slash",
          "fa fa-bell-slash-o",
          "fa fa-bicycle",
          "fa fa-binoculars",
          "fa fa-birthday-cake",
          "fa fa-bitbucket",
          "fa fa-bitbucket-square",
          "fa fa-bitcoin",
          "fa fa-black-tie",
          "fa fa-bluetooth",
          "fa fa-bluetooth-b",
          "fa fa-bold",
          "fa fa-bolt",
          "fa fa-bomb",
          "fa fa-book",
          "fa fa-bookmark",
          "fa fa-bookmark-o",
          "fa fa-braille",
          "fa fa-briefcase",
          "fa fa-btc",
          "fa fa-bug",
          "fa fa-building",
          "fa fa-building-o",
          "fa fa-bullhorn",
          "fa fa-bullseye",
          "fa fa-bus",
          "fa fa-buysellads",
          "fa fa-cab",
          "fa fa-calculator",
          "fa fa-calendar",
          "fa fa-calendar-check-o",
          "fa fa-calendar-minus-o",
          "fa fa-calendar-o",
          "fa fa-calendar-plus-o",
          "fa fa-calendar-times-o",
          "fa fa-camera",
          "fa fa-camera-retro",
          "fa fa-car",
          "fa fa-caret-down",
          "fa fa-caret-left",
          "fa fa-caret-right",
          "fa fa-caret-square-o-down",
          "fa fa-caret-square-o-left",
          "fa fa-caret-square-o-right",
          "fa fa-caret-square-o-up",
          "fa fa-caret-up",
          "fa fa-cart-arrow-down",
          "fa fa-cart-plus",
          "fa fa-cc",
          "fa fa-cc-amex",
          "fa fa-cc-diners-club",
          "fa fa-cc-discover",
          "fa fa-cc-jcb",
          "fa fa-cc-mastercard",
          "fa fa-cc-paypal",
          "fa fa-cc-stripe",
          "fa fa-cc-visa",
          "fa fa-certificate",
          "fa fa-chain",
          "fa fa-chain-broken",
          "fa fa-check",
          "fa fa-check-circle",
          "fa fa-check-circle-o",
          "fa fa-check-square",
          "fa fa-check-square-o",
          "fa fa-chevron-circle-down",
          "fa fa-chevron-circle-left",
          "fa fa-chevron-circle-right",
          "fa fa-chevron-circle-up",
          "fa fa-chevron-down",
          "fa fa-chevron-left",
          "fa fa-chevron-right",
          "fa fa-chevron-up",
          "fa fa-child",
          "fa fa-chrome",
          "fa fa-circle",
          "fa fa-circle-o",
          "fa fa-circle-o-notch",
          "fa fa-circle-thin",
          "fa fa-clipboard",
          "fa fa-clock-o",
          "fa fa-clone",
          "fa fa-close",
          "fa fa-cloud",
          "fa fa-cloud-download",
          "fa fa-cloud-upload",
          "fa fa-cny",
          "fa fa-code",
          "fa fa-code-fork",
          "fa fa-codepen",
          "fa fa-codiepie",
          "fa fa-coffee",
          "fa fa-cog",
          "fa fa-cogs",
          "fa fa-columns",
          "fa fa-comment",
          "fa fa-comment-o",
          "fa fa-commenting",
          "fa fa-commenting-o",
          "fa fa-comments",
          "fa fa-comments-o",
          "fa fa-compass",
          "fa fa-compress",
          "fa fa-connectdevelop",
          "fa fa-contao",
          "fa fa-copy",
          "fa fa-copyright",
          "fa fa-creative-commons",
          "fa fa-credit-card",
          "fa fa-credit-card-alt",
          "fa fa-crop",
          "fa fa-crosshairs",
          "fa fa-css3",
          "fa fa-cube",
          "fa fa-cubes",
          "fa fa-cut",
          "fa fa-cutlery",
          "fa fa-dashboard",
          "fa fa-dashcube",
          "fa fa-database",
          "fa fa-deaf",
          "fa fa-deafness",
          "fa fa-dedent",
          "fa fa-delicious",
          "fa fa-desktop",
          "fa fa-deviantart",
          "fa fa-diamond",
          "fa fa-digg",
          "fa fa-dollar",
          "fa fa-dot-circle-o",
          "fa fa-download",
          "fa fa-dribbble",
          "fa fa-dropbox",
          "fa fa-drupal",
          "fa fa-edge",
          "fa fa-edit",
          "fa fa-eject",
          "fa fa-ellipsis-h",
          "fa fa-ellipsis-v",
          "fa fa-empire",
          "fa fa-envelope",
          "fa fa-envelope-o",
          "fa fa-envelope-square",
          "fa fa-eraser",
          "fa fa-eur",
          "fa fa-euro",
          "fa fa-exchange",
          "fa fa-exclamation",
          "fa fa-exclamation-circle",
          "fa fa-exclamation-triangle",
          "fa fa-expand",
          "fa fa-expeditedssl",
          "fa fa-external-link",
          "fa fa-external-link-square",
          "fa fa-eye",
          "fa fa-eye-slash",
          "fa fa-eyedropper",
          "fa fa-facebook",
          "fa fa-facebook-f",
          "fa fa-facebook-official",
          "fa fa-facebook-square",
          "fa fa-fast-backward",
          "fa fa-fast-forward",
          "fa fa-fax",
          "fa fa-feed",
          "fa fa-female",
          "fa fa-fighter-jet",
          "fa fa-file",
          "fa fa-file-archive-o",
          "fa fa-file-audio-o",
          "fa fa-file-code-o",
          "fa fa-file-excel-o",
          "fa fa-file-image-o",
          "fa fa-file-movie-o",
          "fa fa-file-o",
          "fa fa-file-pdf-o",
          "fa fa-file-photo-o",
          "fa fa-file-picture-o",
          "fa fa-file-powerpoint-o",
          "fa fa-file-sound-o",
          "fa fa-file-text",
          "fa fa-file-text-o",
          "fa fa-file-video-o",
          "fa fa-file-word-o",
          "fa fa-file-zip-o",
          "fa fa-files-o",
          "fa fa-film",
          "fa fa-filter",
          "fa fa-fire",
          "fa fa-fire-extinguisher",
          "fa fa-firefox",
          "fa fa-flag",
          "fa fa-flag-checkered",
          "fa fa-flag-o",
          "fa fa-flash",
          "fa fa-flask",
          "fa fa-flickr",
          "fa fa-floppy-o",
          "fa fa-folder",
          "fa fa-folder-o",
          "fa fa-folder-open",
          "fa fa-folder-open-o",
          "fa fa-font",
          "fa fa-fonticons",
          "fa fa-fort-awesome",
          "fa fa-forumbee",
          "fa fa-forward",
          "fa fa-foursquare",
          "fa fa-frown-o",
          "fa fa-futbol-o",
          "fa fa-gamepad",
          "fa fa-gavel",
          "fa fa-gbp",
          "fa fa-ge",
          "fa fa-gear",
          "fa fa-gears",
          "fa fa-genderless",
          "fa fa-get-pocket",
          "fa fa-gg",
          "fa fa-gg-circle",
          "fa fa-gift",
          "fa fa-git",
          "fa fa-git-square",
          "fa fa-github",
          "fa fa-github-alt",
          "fa fa-github-square",
          "fa fa-gittip",
          "fa fa-glass",
          "fa fa-glide",
          "fa fa-glide-g",
          "fa fa-globe",
          "fa fa-google",
          "fa fa-google-plus",
          "fa fa-google-plus-square",
          "fa fa-google-wallet",
          "fa fa-graduation-cap",
          "fa fa-gratipay",
          "fa fa-group",
          "fa fa-h-square",
          "fa fa-hacker-news",
          "fa fa-hand-grab-o",
          "fa fa-hand-lizard-o",
          "fa fa-hand-o-down",
          "fa fa-hand-o-left",
          "fa fa-hand-o-right",
          "fa fa-hand-o-up",
          "fa fa-hand-paper-o",
          "fa fa-hand-peace-o",
          "fa fa-hand-pointer-o",
          "fa fa-hand-rock-o",
          "fa fa-hand-scissors-o",
          "fa fa-hand-spock-o",
          "fa fa-hand-stop-o",
          "fa fa-hard-of-hearing",
          "fa fa-hashtag",
          "fa fa-hdd-o",
          "fa fa-header",
          "fa fa-headphones",
          "fa fa-heart",
          "fa fa-heart-o",
          "fa fa-heartbeat",
          "fa fa-history",
          "fa fa-home",
          "fa fa-hospital-o",
          "fa fa-hotel",
          "fa fa-hourglass",
          "fa fa-hourglass-1",
          "fa fa-hourglass-2",
          "fa fa-hourglass-3",
          "fa fa-hourglass-end",
          "fa fa-hourglass-half",
          "fa fa-hourglass-o",
          "fa fa-hourglass-start",
          "fa fa-houzz",
          "fa fa-html5",
          "fa fa-i-cursor",
          "fa fa-ils",
          "fa fa-image",
          "fa fa-inbox",
          "fa fa-indent",
          "fa fa-industry",
          "fa fa-info",
          "fa fa-info-circle",
          "fa fa-inr",
          "fa fa-instagram",
          "fa fa-institution",
          "fa fa-internet-explorer",
          "fa fa-intersex",
          "fa fa-ioxhost",
          "fa fa-italic",
          "fa fa-joomla",
          "fa fa-jpy",
          "fa fa-jsfiddle",
          "fa fa-key",
          "fa fa-keyboard-o",
          "fa fa-krw",
          "fa fa-language",
          "fa fa-laptop",
          "fa fa-lastfm",
          "fa fa-lastfm-square",
          "fa fa-leaf",
          "fa fa-leanpub",
          "fa fa-legal",
          "fa fa-lemon-o",
          "fa fa-level-down",
          "fa fa-level-up",
          "fa fa-life-bouy",
          "fa fa-life-buoy",
          "fa fa-life-ring",
          "fa fa-life-saver",
          "fa fa-lightbulb-o",
          "fa fa-line-chart",
          "fa fa-link",
          "fa fa-linkedin",
          "fa fa-linkedin-square",
          "fa fa-linux",
          "fa fa-list",
          "fa fa-list-alt",
          "fa fa-list-ol",
          "fa fa-list-ul",
          "fa fa-location-arrow",
          "fa fa-lock",
          "fa fa-long-arrow-down",
          "fa fa-long-arrow-left",
          "fa fa-long-arrow-right",
          "fa fa-long-arrow-up",
          "fa fa-low-vision",
          "fa fa-magic",
          "fa fa-magnet",
          "fa fa-mail-forward",
          "fa fa-mail-reply",
          "fa fa-mail-reply-all",
          "fa fa-male",
          "fa fa-map",
          "fa fa-map-marker",
          "fa fa-map-o",
          "fa fa-map-pin",
          "fa fa-map-signs",
          "fa fa-mars",
          "fa fa-mars-double",
          "fa fa-mars-stroke",
          "fa fa-mars-stroke-h",
          "fa fa-mars-stroke-v",
          "fa fa-maxcdn",
          "fa fa-meanpath",
          "fa fa-medium",
          "fa fa-medkit",
          "fa fa-meh-o",
          "fa fa-mercury",
          "fa fa-microphone",
          "fa fa-microphone-slash",
          "fa fa-minus",
          "fa fa-minus-circle",
          "fa fa-minus-square",
          "fa fa-minus-square-o",
          "fa fa-mixcloud",
          "fa fa-mobile",
          "fa fa-mobile-phone",
          "fa fa-modx",
          "fa fa-money",
          "fa fa-moon-o",
          "fa fa-mortar-board",
          "fa fa-motorcycle",
          "fa fa-mouse-pointer",
          "fa fa-music",
          "fa fa-navicon",
          "fa fa-neuter",
          "fa fa-newspaper-o",
          "fa fa-object-group",
          "fa fa-object-ungroup",
          "fa fa-odnoklassniki",
          "fa fa-odnoklassniki-square",
          "fa fa-opencart",
          "fa fa-openid",
          "fa fa-opera",
          "fa fa-optin-monster",
          "fa fa-outdent",
          "fa fa-pagelines",
          "fa fa-paint-brush",
          "fa fa-paper-plane",
          "fa fa-paper-plane-o",
          "fa fa-paperclip",
          "fa fa-paragraph",
          "fa fa-paste",
          "fa fa-pause",
          "fa fa-pause-circle",
          "fa fa-pause-circle-o",
          "fa fa-paw",
          "fa fa-paypal",
          "fa fa-pencil",
          "fa fa-pencil-square",
          "fa fa-pencil-square-o",
          "fa fa-percent",
          "fa fa-phone",
          "fa fa-phone-square",
          "fa fa-photo",
          "fa fa-picture-o",
          "fa fa-pie-chart",
          "fa fa-pied-piper",
          "fa fa-pied-piper-alt",
          "fa fa-pinterest",
          "fa fa-pinterest-p",
          "fa fa-pinterest-square",
          "fa fa-plane",
          "fa fa-play",
          "fa fa-play-circle",
          "fa fa-play-circle-o",
          "fa fa-plug",
          "fa fa-plus",
          "fa fa-plus-circle",
          "fa fa-plus-square",
          "fa fa-plus-square-o",
          "fa fa-power-off",
          "fa fa-print",
          "fa fa-product-hunt",
          "fa fa-puzzle-piece",
          "fa fa-qq",
          "fa fa-qrcode",
          "fa fa-question",
          "fa fa-question-circle",
          "fa fa-quote-left",
          "fa fa-quote-right",
          "fa fa-ra",
          "fa fa-random",
          "fa fa-rebel",
          "fa fa-recycle",
          "fa fa-reddit",
          "fa fa-reddit-alien",
          "fa fa-reddit-square",
          "fa fa-refresh",
          "fa fa-registered",
          "fa fa-remove",
          "fa fa-renren",
          "fa fa-reorder",
          "fa fa-repeat",
          "fa fa-reply",
          "fa fa-reply-all",
          "fa fa-retweet",
          "fa fa-rmb",
          "fa fa-road",
          "fa fa-rocket",
          "fa fa-rotate-left",
          "fa fa-rotate-right",
          "fa fa-rouble",
          "fa fa-rss",
          "fa fa-rss-square",
          "fa fa-rub",
          "fa fa-ruble",
          "fa fa-rupee",
          "fa fa-safari",
          "fa fa-save",
          "fa fa-scissors",
          "fa fa-scribd",
          "fa fa-search",
          "fa fa-search-minus",
          "fa fa-search-plus",
          "fa fa-sellsy",
          "fa fa-send",
          "fa fa-send-o",
          "fa fa-server",
          "fa fa-share",
          "fa fa-share-alt",
          "fa fa-share-alt-square",
          "fa fa-share-square",
          "fa fa-share-square-o",
          "fa fa-shekel",
          "fa fa-sheqel",
          "fa fa-shield",
          "fa fa-ship",
          "fa fa-shirtsinbulk",
          "fa fa-shopping-bag",
          "fa fa-shopping-basket",
          "fa fa-shopping-cart",
          "fa fa-sign-in",
          "fa fa-sign-language",
          "fa fa-sign-out",
          "fa fa-signal",
          "fa fa-signing",
          "fa fa-simplybuilt",
          "fa fa-sitemap",
          "fa fa-skyatlas",
          "fa fa-skype",
          "fa fa-slack",
          "fa fa-sliders",
          "fa fa-slideshare",
          "fa fa-smile-o",
          "fa fa-snapchat",
          "fa fa-snapchat-ghost",
          "fa fa-snapchat-square",
          "fa fa-soccer-ball-o",
          "fa fa-sort",
          "fa fa-sort-alpha-asc",
          "fa fa-sort-alpha-desc",
          "fa fa-sort-amount-asc",
          "fa fa-sort-amount-desc",
          "fa fa-sort-asc",
          "fa fa-sort-desc",
          "fa fa-sort-down",
          "fa fa-sort-numeric-asc",
          "fa fa-sort-numeric-desc",
          "fa fa-sort-up",
          "fa fa-soundcloud",
          "fa fa-space-shuttle",
          "fa fa-spinner",
          "fa fa-spoon",
          "fa fa-spotify",
          "fa fa-square",
          "fa fa-square-o",
          "fa fa-stack-exchange",
          "fa fa-stack-overflow",
          "fa fa-star",
          "fa fa-star-half",
          "fa fa-star-half-empty",
          "fa fa-star-half-full",
          "fa fa-star-half-o",
          "fa fa-star-o",
          "fa fa-steam",
          "fa fa-steam-square",
          "fa fa-step-backward",
          "fa fa-step-forward",
          "fa fa-stethoscope",
          "fa fa-sticky-note",
          "fa fa-sticky-note-o",
          "fa fa-stop",
          "fa fa-stop-circle",
          "fa fa-stop-circle-o",
          "fa fa-street-view",
          "fa fa-strikethrough",
          "fa fa-stumbleupon",
          "fa fa-stumbleupon-circle",
          "fa fa-subscript",
          "fa fa-subway",
          "fa fa-suitcase",
          "fa fa-sun-o",
          "fa fa-superscript",
          "fa fa-support",
          "fa fa-table",
          "fa fa-tablet",
          "fa fa-tachometer",
          "fa fa-tag",
          "fa fa-tags",
          "fa fa-tasks",
          "fa fa-taxi",
          "fa fa-television",
          "fa fa-tencent-weibo",
          "fa fa-terminal",
          "fa fa-text-height",
          "fa fa-text-width",
          "fa fa-th",
          "fa fa-th-large",
          "fa fa-th-list",
          "fa fa-thumb-tack",
          "fa fa-thumbs-down",
          "fa fa-thumbs-o-down",
          "fa fa-thumbs-o-up",
          "fa fa-thumbs-up",
          "fa fa-ticket",
          "fa fa-times",
          "fa fa-times-circle",
          "fa fa-times-circle-o",
          "fa fa-tint",
          "fa fa-toggle-down",
          "fa fa-toggle-left",
          "fa fa-toggle-off",
          "fa fa-toggle-on",
          "fa fa-toggle-right",
          "fa fa-toggle-up",
          "fa fa-trademark",
          "fa fa-train",
          "fa fa-transgender",
          "fa fa-transgender-alt",
          "fa fa-trash",
          "fa fa-trash-o",
          "fa fa-tree",
          "fa fa-trello",
          "fa fa-tripadvisor",
          "fa fa-trophy",
          "fa fa-truck",
          "fa fa-try",
          "fa fa-tty",
          "fa fa-tumblr",
          "fa fa-tumblr-square",
          "fa fa-turkish-lira",
          "fa fa-tv",
          "fa fa-twitch",
          "fa fa-twitter",
          "fa fa-twitter-square",
          "fa fa-umbrella",
          "fa fa-underline",
          "fa fa-undo",
          "fa fa-university",
          "fa fa-unlink",
          "fa fa-unlock",
          "fa fa-unlock-alt",
          "fa fa-unsorted",
          "fa fa-upload",
          "fa fa-usb",
          "fa fa-usd",
          "fa fa-user",
          "fa fa-user-md",
          "fa fa-user-plus",
          "fa fa-user-secret",
          "fa fa-user-times",
          "fa fa-users",
          "fa fa-venus",
          "fa fa-venus-double",
          "fa fa-venus-mars",
          "fa fa-viacoin",
          "fa fa-viadeo",
          "fa fa-viadeo-square",
          "fa fa-video-camera",
          "fa fa-vimeo",
          "fa fa-vimeo-square",
          "fa fa-vine",
          "fa fa-vk",
          "fa fa-volume-control-phone",
          "fa fa-volume-down",
          "fa fa-volume-off",
          "fa fa-volume-up",
          "fa fa-warning",
          "fa fa-wechat",
          "fa fa-weibo",
          "fa fa-weixin",
          "fa fa-whatsapp",
          "fa fa-wheelchair",
          "fa fa-wifi",
          "fa fa-wikipedia-w",
          "fa fa-windows",
          "fa fa-won",
          "fa fa-wordpress",
          "fa fa-wrench",
          "fa fa-xing",
          "fa fa-xing-square",
          "fa fa-y-combinator",
          "fa fa-y-combinator-square",
          "fa fa-yahoo",
          "fa fa-yc",
          "fa fa-yc-square",
          "fa fa-yelp",
          "fa fa-yen",
          "fa fa-youtube",
          "fa fa-youtube-play",
          "fa fa-youtube-square",

        );

        return apply_filters('dental_care_fontawesomeicons_array', $awesome_icons);
    }

}


if (!function_exists('dental_care_linearicons_array')) {


        function dental_care_linearicons_array() {

        $linear_icons = array(
             "lnr lnr-home",
             "lnr lnr-apartment",
             "lnr lnr-pencil",
             "lnr lnr-magic-wand",
             "lnr lnr-drop",
             "lnr lnr-lighter",
             "lnr lnr-poop",
             "lnr lnr-sun",
             "lnr lnr-moon",
             "lnr lnr-cloud",
             "lnr lnr-cloud-upload",
             "lnr lnr-cloud-download",
             "lnr lnr-cloud-sync",
             "lnr lnr-cloud-check",
             "lnr lnr-database",
            "lnr lnr-lock",
            "lnr lnr-cog",
            "lnr lnr-trash",
            "lnr lnr-dice",
            "lnr lnr-heart",
            "lnr lnr-star",
            "lnr lnr-star-half",
            "lnr lnr-star-empty",
            "lnr lnr-flag",
            "lnr lnr-envelope",
            "lnr lnr-paperclip",
            "lnr lnr-inbox",
            "lnr lnr-eye",
            "lnr lnr-printer",
            "lnr lnr-file-empty",
            "lnr lnr-file-add",
            "lnr lnr-enter",
            "lnr lnr-exit",
            "lnr lnr-graduation-hat",
            "lnr lnr-license",
            "lnr lnr-music-note",
            "lnr lnr-film-play",
            "lnr lnr-camera-video",
            "lnr lnr-camera",
            "lnr lnr-picture",
            "lnr lnr-book",
            "lnr lnr-bookmark",
            "lnr lnr-user",
            "lnr lnr-users",
            "lnr lnr-shirt",
            "lnr lnr-store",
            "lnr lnr-cart",
            "lnr lnr-tag",
            "lnr lnr-phone-handset",
            "lnr lnr-phone",
            "lnr lnr-pushpin",
            "lnr lnr-map-marker",
            "lnr lnr-map",
            "lnr lnr-location",
            "lnr lnr-calendar-full",
            "lnr lnr-keyboard",
            "lnr lnr-spell-check",
            "lnr lnr-screen",
            "lnr lnr-smartphone",
            "lnr lnr-tablet",
            "lnr lnr-laptop",
            "lnr lnr-laptop-phone",
            "lnr lnr-power-switch",
            "lnr lnr-bubble",
            "lnr lnr-heart-pulse",
            "lnr lnr-construction",
            "lnr lnr-pie-chart",
            "lnr lnr-chart-bars",
            "lnr lnr-gift",
            "lnr lnr-diamond",
            "lnr lnr-linearicons",
            "lnr lnr-dinner",
            "lnr lnr-coffee-cup",
            "lnr lnr-leaf",
            "lnr lnr-paw",
            "lnr lnr-rocket",
            "lnr lnr-briefcase",
            "lnr lnr-bus",
            "lnr lnr-car",
            "lnr lnr-train",
            "lnr lnr-bicycle",
            "lnr lnr-wheelchair",
            "lnr lnr-select",
            "lnr lnr-earth",
            "lnr lnr-smile",
            "lnr lnr-sad",
            "lnr lnr-neutral",
            "lnr lnr-mustache",
            "lnr lnr-alarm",
            "lnr lnr-bullhorn",
            "lnr lnr-volume-high",
            "lnr lnr-volume-medium",
            "lnr lnr-volume-low",
            "lnr lnr-volume",
            "lnr lnr-mic",
            "lnr lnr-hourglass",
            "lnr lnr-undo",
            "lnr lnr-redo",
            "lnr lnr-sync",
            "lnr lnr-history",
            "lnr lnr-clock",
            "lnr lnr-download",
            "lnr lnr-upload",
            "lnr lnr-enter-down",
            "lnr lnr-exit-up",
            "lnr lnr-bug",
            "lnr lnr-code",
            "lnr lnr-link",
            "lnr lnr-unlink",
            "lnr lnr-thumbs-up",
            "lnr lnr-thumbs-down",
            "lnr lnr-magnifier",
            "lnr lnr-cross",
            "lnr lnr-menu",
            "lnr lnr-list",
            "lnr lnr-chevron-up",
            "lnr lnr-chevron-down",
            "lnr lnr-chevron-left",
            "lnr lnr-chevron-right",
            "lnr lnr-arrow-up",
            "lnr lnr-arrow-down",
            "lnr lnr-arrow-left",
            "lnr lnr-arrow-right",
            "lnr lnr-move",
            "lnr lnr-warning",
            "lnr lnr-question-circle",
            "lnr lnr-menu-circle",
            "lnr lnr-checkmark-circle",
            "lnr lnr-cross-circle",
            "lnr lnr-plus-circle",
            "lnr lnr-circle-minus",
            "lnr lnr-arrow-up-circle",
            "lnr lnr-arrow-down-circle",
            "lnr lnr-arrow-left-circle",
            "lnr lnr-arrow-right-circle",
            "lnr lnr-chevron-up-circle",
            "lnr lnr-chevron-down-circle",
            "lnr lnr-chevron-left-circle",
            "lnr lnr-chevron-right-circle",
            "lnr lnr-crop",
            "lnr lnr-frame-expand",
            "lnr lnr-frame-contract",
            "lnr lnr-layers",
            "lnr lnr-funnel",
            "lnr lnr-text-format",
            "lnr lnr-text-format-remove",
            "lnr lnr-text-size",
            "lnr lnr-bold",
            "lnr lnr-italic",
            "lnr lnr-underline",
            "lnr lnr-strikethrough",
            "lnr lnr-highlight",
            "lnr lnr-text-align-left",
            "lnr lnr-text-align-center",
            "lnr lnr-text-align-right",
            "lnr lnr-text-align-justify",
            "lnr lnr-line-spacing",
            "lnr lnr-indent-increase",
            "lnr lnr-indent-decrease",
            "lnr lnr-pilcrow",
            "lnr lnr-direction-ltr",
            "lnr lnr-direction-rtl",
            "lnr lnr-page-break",
            "lnr lnr-sort-alpha-asc",
            "lnr lnr-sort-amount-asc",
            "lnr lnr-hand",
            "lnr lnr-pointer-up",
            "lnr lnr-pointer-right",
            "lnr lnr-pointer-down",
            "lnr lnr-pointer-left",

        );

        return apply_filters('dental_care_linearicons_array', $linear_icons);
    }

}

if (!function_exists('dental_care_themify_array')) {

    function dental_care_themify_array() {

        $icons_themify = array(
            "ti-wand",
            "ti-volume",
            "ti-user",
            "ti-unlock",
            "ti-unlink",
            "ti-trash",
            "ti-thought",
            "ti-target",
            "ti-tag",
            "ti-tablet",
            "ti-star",
            "ti-spray",
            "ti-signal",
            "ti-shopping-cart",
            "ti-shopping-cart-full",
            "ti-settings",
            "ti-search",
            "ti-zoom-in",
            "ti-zoom-out",
            "ti-cut",
            "ti-ruler",
            "ti-ruler-pencil",
            "ti-ruler-alt",
            "ti-bookmark",
            "ti-bookmark-alt",
            "ti-reload",
            "ti-plus",
            "ti-pin",
            "ti-pencil",
            "ti-pencil-alt",
            "ti-paint-roller",
            "ti-paint-bucket",
            "ti-na",
            "ti-mobile",
            "ti-minus",
            "ti-medall",
            "ti-medall-alt",
            "ti-marker",
            "ti-marker-alt",
            "ti-arrow-up",
            "ti-arrow-right",
            "ti-arrow-left",
            "ti-arrow-down",
            "ti-lock",
            "ti-location-arrow",
            "ti-link",
            "ti-layout",
            "ti-layers",
            "ti-layers-alt",
            "ti-key",
            "ti-import",
            "ti-image",
            "ti-heart",
            "ti-heart-broken",
            "ti-hand-stop",
            "ti-hand-open",
            "ti-hand-drag",
            "ti-folder",
            "ti-flag",
            "ti-flag-alt",
            "ti-flag-alt-2",
            "ti-eye",
            "ti-export",
            "ti-exchange-vertical",
            "ti-desktop",
            "ti-cup",
            "ti-crown",
            "ti-comments",
            "ti-comment",
            "ti-comment-alt",
            "ti-close",
            "ti-clip",
            "ti-angle-up",
            "ti-angle-right",
            "ti-angle-left",
            "ti-angle-down",
            "ti-check",
            "ti-check-box",
            "ti-camera",
            "ti-announcement",
            "ti-brush",
            "ti-briefcase",
            "ti-bolt",
            "ti-bolt-alt",
            "ti-blackboard",
            "ti-bag",
            "ti-move",
            "ti-arrows-vertical",
            "ti-arrows-horizontal",
            "ti-fullscreen",
            "ti-arrow-top-right",
            "ti-arrow-top-left",
            "ti-arrow-circle-up",
            "ti-arrow-circle-right",
            "ti-arrow-circle-left",
            "ti-arrow-circle-down",
            "ti-angle-double-up",
            "ti-angle-double-right",
            "ti-angle-double-left",
            "ti-angle-double-down",
            "ti-zip",
            "ti-world",
            "ti-wheelchair",
            "ti-view-list",
            "ti-view-list-alt",
            "ti-view-grid",
            "ti-uppercase",
            "ti-upload",
            "ti-underline",
            "ti-truck",
            "ti-timer",
            "ti-ticket",
            "ti-thumb-up",
            "ti-thumb-down",
            "ti-text",
            "ti-stats-up",
            "ti-stats-down",
            "ti-split-v",
            "ti-split-h",
            "ti-smallcap",
            "ti-shine",
            "ti-shift-right",
            "ti-shift-left",
            "ti-shield",
            "ti-notepad",
            "ti-server",
            "ti-quote-right",
            "ti-quote-left",
            "ti-pulse",
            "ti-printer",
            "ti-power-off",
            "ti-plug",
            "ti-pie-chart",
            "ti-paragraph",
            "ti-panel",
            "ti-package",
            "ti-music",
            "ti-music-alt",
            "ti-mouse",
            "ti-mouse-alt",
            "ti-money",
            "ti-microphone",
            "ti-menu",
            "ti-menu-alt",
            "ti-map",
            "ti-map-alt",
            "ti-loop",
            "ti-location-pin",
            "ti-list",
            "ti-light-bulb",
            "ti-Italic",
            "ti-info",
            "ti-infinite",
            "ti-id-badge",
            "ti-hummer",
            "ti-home",
            "ti-help",
            "ti-headphone",
            "ti-harddrives",
            "ti-harddrive",
            "ti-gift",
            "ti-game",
            "ti-filter",
            "ti-files",
            "ti-file",
            "ti-eraser",
            "ti-envelope",
            "ti-download",
            "ti-direction",
            "ti-direction-alt",
            "ti-dashboard",
            "ti-control-stop",
            "ti-control-shuffle",
            "ti-control-play",
            "ti-control-pause",
            "ti-control-forward",
            "ti-control-backward",
            "ti-cloud",
            "ti-cloud-up",
            "ti-cloud-down",
            "ti-clipboard",
            "ti-car",
            "ti-calendar",
            "ti-book",
            "ti-bell",
            "ti-basketball",
            "ti-bar-chart",
            "ti-bar-chart-alt",
            "ti-back-right",
            "ti-back-left",
            "ti-arrows-corner",
            "ti-archive",
            "ti-anchor",
            "ti-align-right",
            "ti-align-left",
            "ti-align-justify",
            "ti-align-center",
            "ti-alert",
            "ti-alarm-clock",
            "ti-agenda",
            "ti-write",
            "ti-window",
            "ti-widgetized",
            "ti-widget",
            "ti-widget-alt",
            "ti-wallet",
            "ti-video-clapper",
            "ti-video-camera",
            "ti-vector",
            "ti-themify-logo",
            "ti-themify-favicon",
            "ti-themify-favicon-alt",
            "ti-support",
            "ti-stamp",
            "ti-split-v-alt",
            "ti-slice",
            "ti-shortcode",
            "ti-shift-right-alt",
            "ti-shift-left-alt",
            "ti-ruler-alt-2",
            "ti-receipt",
            "ti-pin2",
            "ti-pin-alt",
            "ti-pencil-alt2",
            "ti-palette",
            "ti-more",
            "ti-more-alt",
            "ti-microphone-alt",
            "ti-magnet",
            "ti-line-double",
            "ti-line-dotted",
            "ti-line-dashed",
            "ti-layout-width-full",
            "ti-layout-width-default",
            "ti-layout-width-default-alt",
            "ti-layout-tab",
            "ti-layout-tab-window",
            "ti-layout-tab-v",
            "ti-layout-tab-min",
            "ti-layout-slider",
            "ti-layout-slider-alt",
            "ti-layout-sidebar-right",
            "ti-layout-sidebar-none",
            "ti-layout-sidebar-left",
            "ti-layout-placeholder",
            "ti-layout-menu",
            "ti-layout-menu-v",
            "ti-layout-menu-separated",
            "ti-layout-menu-full",
            "ti-layout-media-right-alt",
            "ti-layout-media-right",
            "ti-layout-media-overlay",
            "ti-layout-media-overlay-alt",
            "ti-layout-media-overlay-alt-2",
            "ti-layout-media-left-alt",
            "ti-layout-media-left",
            "ti-layout-media-center-alt",
            "ti-layout-media-center",
            "ti-layout-list-thumb",
            "ti-layout-list-thumb-alt",
            "ti-layout-list-post",
            "ti-layout-list-large-image",
            "ti-layout-line-solid",
            "ti-layout-grid4",
            "ti-layout-grid3",
            "ti-layout-grid2",
            "ti-layout-grid2-thumb",
            "ti-layout-cta-right",
            "ti-layout-cta-left",
            "ti-layout-cta-center",
            "ti-layout-cta-btn-right",
            "ti-layout-cta-btn-left",
            "ti-layout-column4",
            "ti-layout-column3",
            "ti-layout-column2",
            "ti-layout-accordion-separated",
            "ti-layout-accordion-merged",
            "ti-layout-accordion-list",
            "ti-ink-pen",
            "ti-info-alt",
            "ti-help-alt",
            "ti-headphone-alt",
            "ti-hand-point-up",
            "ti-hand-point-right",
            "ti-hand-point-left",
            "ti-hand-point-down",
            "ti-gallery",
            "ti-face-smile",
            "ti-face-sad",
            "ti-credit-card",
            "ti-control-skip-forward",
            "ti-control-skip-backward",
            "ti-control-record",
            "ti-control-eject",
            "ti-comments-smiley",
            "ti-brush-alt",
            "ti-youtube",
            "ti-vimeo",
            "ti-twitter",
            "ti-time",
            "ti-tumblr",
            "ti-skype",
            "ti-share",
            "ti-share-alt",
            "ti-rocket",
            "ti-pinterest",
            "ti-new-window",
            "ti-microsoft",
            "ti-list-ol",
            "ti-linkedin",
            "ti-layout-sidebar-2",
            "ti-layout-grid4-alt",
            "ti-layout-grid3-alt",
            "ti-layout-grid2-alt",
            "ti-layout-column4-alt",
            "ti-layout-column3-alt",
            "ti-layout-column2-alt",
            "ti-instagram",
            "ti-google",
            "ti-github",
            "ti-flickr",
            "ti-facebook",
            "ti-dropbox",
            "ti-dribbble",
            "ti-apple",
            "ti-android",
            "ti-save",
            "ti-save-alt",
            "ti-yahoo",
            "ti-wordpress",
            "ti-vimeo-alt",
            "ti-twitter-alt",
            "ti-tumblr-alt",
            "ti-trello",
            "ti-stack-overflow",
            "ti-soundcloud",
            "ti-sharethis",
            "ti-sharethis-alt",
            "ti-reddit",
            "ti-pinterest-alt",
            "ti-microsoft-alt",
            "ti-linux",
            "ti-jsfiddle",
            "ti-joomla",
            "ti-html5",
            "ti-flickr-alt",
            "ti-email",
            "ti-drupal",
            "ti-dropbox-alt",
            "ti-css3",
            "ti-rss",
            "ti-rss-alt"
        );
        return apply_filters('dental_care_themify_array', $icons_themify);
    }

}


if (!function_exists('dental_care_ionicon_array')) {

    function dental_care_ionicon_array() {

        $ionicons = array(
            "icon ion-ionic",
            "icon ion-arrow-up-a",
            "icon ion-arrow-right-a",
            "icon ion-arrow-down-a",
            "icon ion-arrow-left-a",
            "icon ion-arrow-up-b",
            "icon ion-arrow-right-b",
            "icon ion-arrow-down-b",
            "icon ion-arrow-left-b",
            "icon ion-arrow-up-c",
            "icon ion-arrow-right-c",
            "icon ion-arrow-down-c",
            "icon ion-arrow-left-c",
            "icon ion-arrow-return-right",
            "icon ion-arrow-return-left",
            "icon ion-arrow-swap",
            "icon ion-arrow-shrink",
            "icon ion-arrow-expand",
            "icon ion-arrow-move",
            "icon ion-arrow-resize",
            "icon ion-chevron-up",
            "icon ion-chevron-right",
            "icon ion-chevron-down",
            "icon ion-chevron-left",
            "icon ion-navicon-round",
            "icon ion-navicon",
            "icon ion-drag",
            "icon ion-log-in",
            "icon ion-log-out",
            "icon ion-checkmark-round",
            "icon ion-checkmark",
            "icon ion-checkmark-circled",
            "icon ion-close-round",
            "icon ion-close",
            "icon ion-close-circled",
            "icon ion-plus-round",
            "icon ion-plus",
            "icon ion-plus-circled",
            "icon ion-minus-round",
            "icon ion-minus",
            "icon ion-minus-circled",
            "icon ion-information",
            "icon ion-information-circled",
            "icon ion-help",
            "icon ion-help-circled",
            "icon ion-backspace-outline",
            "icon ion-backspace",
            "icon ion-help-buoy",
            "icon ion-asterisk",
            "icon ion-alert",
            "icon ion-alert-circled",
            "icon ion-refresh",
            "icon ion-loop",
            "icon ion-shuffle",
            "icon ion-home",
            "icon ion-search",
            "icon ion-flag",
            "icon ion-star",
            "icon ion-heart",
            "icon ion-heart-broken",
            "icon ion-gear-a",
            "icon ion-gear-b",
            "icon ion-toggle-filled",
            "icon ion-toggle",
            "icon ion-settings",
            "icon ion-wrench",
            "icon ion-hammer",
            "icon ion-edit",
            "icon ion-trash-a",
            "icon ion-trash-b",
            "icon ion-document",
            "icon ion-document-text",
            "icon ion-clipboard",
            "icon ion-scissors",
            "icon ion-funnel",
            "icon ion-bookmark",
            "icon ion-email",
            "icon ion-email-unread",
            "icon ion-folder",
            "icon ion-filing",
            "icon ion-archive",
            "icon ion-reply",
            "icon ion-reply-all",
            "icon ion-forward",
            "icon ion-share",
            "icon ion-paper-airplane",
            "icon ion-link",
            "icon ion-paperclip",
            "icon ion-compose",
            "icon ion-briefcase",
            "icon ion-medkit",
            "icon ion-at",
            "icon ion-pound",
            "icon ion-quote",
            "icon ion-cloud",
            "icon ion-upload",
            "icon ion-more",
            "icon ion-grid",
            "icon ion-calendar",
            "icon ion-clock",
            "icon ion-compass",
            "icon ion-pinpoint",
            "icon ion-pin",
            "icon ion-navigate",
            "icon ion-location",
            "icon ion-map",
            "icon ion-lock-combination",
            "icon ion-locked",
            "icon ion-unlocked",
            "icon ion-key",
            "icon ion-arrow-graph-up-right",
            "icon ion-arrow-graph-down-right",
            "icon ion-arrow-graph-up-left",
            "icon ion-arrow-graph-down-left",
            "icon ion-stats-bars",
            "icon ion-connection-bars",
            "icon ion-pie-graph",
            "icon ion-chatbubble",
            "icon ion-chatbubble-working",
            "icon ion-chatbubbles",
            "icon ion-chatbox",
            "icon ion-chatbox-working",
            "icon ion-chatboxes",
            "icon ion-person",
            "icon ion-person-add",
            "icon ion-person-stalker",
            "icon ion-woman",
            "icon ion-man",
            "icon ion-female",
            "icon ion-male",
            "icon ion-transgender",
            "icon ion-fork",
            "icon ion-knife",
            "icon ion-spoon",
            "icon ion-soup-can-outline",
            "icon ion-soup-can",
            "icon ion-beer",
            "icon ion-wineglass",
            "icon ion-coffee",
            "icon ion-icecream",
            "icon ion-pizza",
            "icon ion-power",
            "icon ion-mouse",
            "icon ion-battery-full",
            "icon ion-battery-half",
            "icon ion-battery-low",
            "icon ion-battery-empty",
            "icon ion-battery-charging",
            "icon ion-wifi",
            "icon ion-bluetooth",
            "icon ion-calculator",
            "icon ion-camera",
            "icon ion-eye",
            "icon ion-eye-disabled",
            "icon ion-flash",
            "icon ion-flash-off",
            "icon ion-qr-scanner",
            "icon ion-image",
            "icon ion-images",
            "icon ion-wand",
            "icon ion-contrast",
            "icon ion-aperture",
            "icon ion-crop",
            "icon ion-easel",
            "icon ion-paintbrush",
            "icon ion-paintbucket",
            "icon ion-monitor",
            "icon ion-laptop",
            "icon ion-ipad",
            "icon ion-iphone",
            "icon ion-ipod",
            "icon ion-printer",
            "icon ion-usb",
            "icon ion-outlet",
            "icon ion-bug",
            "icon ion-code",
            "icon ion-code-working",
            "icon ion-code-download",
            "icon ion-fork-repo",
            "icon ion-network",
            "icon ion-pull-request",
            "icon ion-merge",
            "icon ion-xbox",
            "icon ion-playstation",
            "icon ion-steam",
            "icon ion-closed-captioning",
            "icon ion-videocamera",
            "icon ion-film-marker",
            "icon ion-disc",
            "icon ion-headphone",
            "icon ion-music-note",
            "icon ion-radio-waves",
            "icon ion-speakerphone",
            "icon ion-mic-a",
            "icon ion-mic-b",
            "icon ion-mic-c",
            "icon ion-volume-high",
            "icon ion-volume-medium",
            "icon ion-volume-low",
            "icon ion-volume-mute",
            "icon ion-levels",
            "icon ion-play",
            "icon ion-pause",
            "icon ion-stop",
            "icon ion-record",
            "icon ion-skip-forward",
            "icon ion-skip-backward",
            "icon ion-eject",
            "icon ion-bag",
            "icon ion-card",
            "icon ion-cash",
            "icon ion-pricetag",
            "icon ion-pricetags",
            "icon ion-thumbsup",
            "icon ion-thumbsdown",
            "icon ion-happy-outline",
            "icon ion-happy",
            "icon ion-sad-outline",
            "icon ion-sad",
            "icon ion-bowtie",
            "icon ion-tshirt-outline",
            "icon ion-tshirt",
            "icon ion-trophy",
            "icon ion-podium",
            "icon ion-ribbon-a",
            "icon ion-ribbon-b",
            "icon ion-university",
            "icon ion-magnet",
            "icon ion-beaker",
            "icon ion-erlenmeyer-flask",
            "icon ion-egg",
            "icon ion-earth",
            "icon ion-planet",
            "icon ion-lightbulb",
            "icon ion-cube",
            "icon ion-leaf",
            "icon ion-waterdrop",
            "icon ion-flame",
            "icon ion-fireball",
            "icon ion-bonfire",
            "icon ion-umbrella",
            "icon ion-nuclear",
            "icon ion-no-smoking",
            "icon ion-thermometer",
            "icon ion-speedometer",
            "icon ion-model-s",
            "icon ion-plane",
            "icon ion-jet",
            "icon ion-load-a",
            "icon ion-load-b",
            "icon ion-load-c",
            "icon ion-load-d",
            "icon ion-ios-ionic-outline",
            "icon ion-ios-arrow-back",
            "icon ion-ios-arrow-forward",
            "icon ion-ios-arrow-up",
            "icon ion-ios-arrow-right",
            "icon ion-ios-arrow-down",
            "icon ion-ios-arrow-left",
            "icon ion-ios-arrow-thin-up",
            "icon ion-ios-arrow-thin-right",
            "icon ion-ios-arrow-thin-down",
            "icon ion-ios-arrow-thin-left",
            "icon ion-ios-circle-filled",
            "icon ion-ios-circle-outline",
            "icon ion-ios-checkmark-empty",
            "icon ion-ios-checkmark-outline",
            "icon ion-ios-checkmark",
            "icon ion-ios-plus-empty",
            "icon ion-ios-plus-outline",
            "icon ion-ios-plus",
            "icon ion-ios-close-empty",
            "icon ion-ios-close-outline",
            "icon ion-ios-close",
            "icon ion-ios-minus-empty",
            "icon ion-ios-minus-outline",
            "icon ion-ios-minus",
            "icon ion-ios-information-empty",
            "icon ion-ios-information-outline",
            "icon ion-ios-information",
            "icon ion-ios-help-empty",
            "icon ion-ios-help-outline",
            "icon ion-ios-help",
            "icon ion-ios-search",
            "icon ion-ios-search-strong",
            "icon ion-ios-star",
            "icon ion-ios-star-half",
            "icon ion-ios-star-outline",
            "icon ion-ios-heart",
            "icon ion-ios-heart-outline",
            "icon ion-ios-more",
            "icon ion-ios-more-outline",
            "icon ion-ios-home",
            "icon ion-ios-home-outline",
            "icon ion-ios-cloud",
            "icon ion-ios-cloud-outline",
            "icon ion-ios-cloud-upload",
            "icon ion-ios-cloud-upload-outline",
            "icon ion-ios-cloud-download",
            "icon ion-ios-cloud-download-outline",
            "icon ion-ios-upload",
            "icon ion-ios-upload-outline",
            "icon ion-ios-download",
            "icon ion-ios-download-outline",
            "icon ion-ios-refresh",
            "icon ion-ios-refresh-outline",
            "icon ion-ios-refresh-empty",
            "icon ion-ios-reload",
            "icon ion-ios-loop-strong",
            "icon ion-ios-loop",
            "icon ion-ios-bookmarks",
            "icon ion-ios-bookmarks-outline",
            "icon ion-ios-book",
            "icon ion-ios-book-outline",
            "icon ion-ios-flag",
            "icon ion-ios-flag-outline",
            "icon ion-ios-glasses",
            "icon ion-ios-glasses-outline",
            "icon ion-ios-browsers",
            "icon ion-ios-browsers-outline",
            "icon ion-ios-at",
            "icon ion-ios-at-outline",
            "icon ion-ios-pricetag",
            "icon ion-ios-pricetag-outline",
            "icon ion-ios-pricetags",
            "icon ion-ios-pricetags-outline",
            "icon ion-ios-cart",
            "icon ion-ios-cart-outline",
            "icon ion-ios-chatboxes",
            "icon ion-ios-chatboxes-outline",
            "icon ion-ios-chatbubble",
            "icon ion-ios-chatbubble-outline",
            "icon ion-ios-cog",
            "icon ion-ios-cog-outline",
            "icon ion-ios-gear",
            "icon ion-ios-gear-outline",
            "icon ion-ios-settings",
            "icon ion-ios-settings-strong",
            "icon ion-ios-toggle",
            "icon ion-ios-toggle-outline",
            "icon ion-ios-analytics",
            "icon ion-ios-analytics-outline",
            "icon ion-ios-pie",
            "icon ion-ios-pie-outline",
            "icon ion-ios-pulse",
            "icon ion-ios-pulse-strong",
            "icon ion-ios-filing",
            "icon ion-ios-filing-outline",
            "icon ion-ios-box",
            "icon ion-ios-box-outline",
            "icon ion-ios-compose",
            "icon ion-ios-compose-outline",
            "icon ion-ios-trash",
            "icon ion-ios-trash-outline",
            "icon ion-ios-copy",
            "icon ion-ios-copy-outline",
            "icon ion-ios-email",
            "icon ion-ios-email-outline",
            "icon ion-ios-undo",
            "icon ion-ios-undo-outline",
            "icon ion-ios-redo",
            "icon ion-ios-redo-outline",
            "icon ion-ios-paperplane",
            "icon ion-ios-paperplane-outline",
            "icon ion-ios-folder",
            "icon ion-ios-folder-outline",
            "icon ion-ios-paper",
            "icon ion-ios-paper-outline",
            "icon ion-ios-list",
            "icon ion-ios-list-outline",
            "icon ion-ios-world",
            "icon ion-ios-world-outline",
            "icon ion-ios-alarm",
            "icon ion-ios-alarm-outline",
            "icon ion-ios-speedometer",
            "icon ion-ios-speedometer-outline",
            "icon ion-ios-stopwatch",
            "icon ion-ios-stopwatch-outline",
            "icon ion-ios-timer",
            "icon ion-ios-timer-outline",
            "icon ion-ios-clock",
            "icon ion-ios-clock-outline",
            "icon ion-ios-time",
            "icon ion-ios-time-outline",
            "icon ion-ios-calendar",
            "icon ion-ios-calendar-outline",
            "icon ion-ios-photos",
            "icon ion-ios-photos-outline",
            "icon ion-ios-albums",
            "icon ion-ios-albums-outline",
            "icon ion-ios-camera",
            "icon ion-ios-camera-outline",
            "icon ion-ios-reverse-camera",
            "icon ion-ios-reverse-camera-outline",
            "icon ion-ios-eye",
            "icon ion-ios-eye-outline",
            "icon ion-ios-bolt",
            "icon ion-ios-bolt-outline",
            "icon ion-ios-color-wand",
            "icon ion-ios-color-wand-outline",
            "icon ion-ios-color-filter",
            "icon ion-ios-color-filter-outline",
            "icon ion-ios-grid-view",
            "icon ion-ios-grid-view-outline",
            "icon ion-ios-crop-strong",
            "icon ion-ios-crop",
            "icon ion-ios-barcode",
            "icon ion-ios-barcode-outline",
            "icon ion-ios-briefcase",
            "icon ion-ios-briefcase-outline",
            "icon ion-ios-medkit",
            "icon ion-ios-medkit-outline",
            "icon ion-ios-medical",
            "icon ion-ios-medical-outline",
            "icon ion-ios-infinite",
            "icon ion-ios-infinite-outline",
            "icon ion-ios-calculator",
            "icon ion-ios-calculator-outline",
            "icon ion-ios-keypad",
            "icon ion-ios-keypad-outline",
            "icon ion-ios-telephone",
            "icon ion-ios-telephone-outline",
            "icon ion-ios-drag",
            "icon ion-ios-location",
            "icon ion-ios-location-outline",
            "icon ion-ios-navigate",
            "icon ion-ios-navigate-outline",
            "icon ion-ios-locked",
            "icon ion-ios-locked-outline",
            "icon ion-ios-unlocked",
            "icon ion-ios-unlocked-outline",
            "icon ion-ios-monitor",
            "icon ion-ios-monitor-outline",
            "icon ion-ios-printer",
            "icon ion-ios-printer-outline",
            "icon ion-ios-game-controller-a",
            "icon ion-ios-game-controller-a-outline",
            "icon ion-ios-game-controller-b",
            "icon ion-ios-game-controller-b-outline",
            "icon ion-ios-americanfootball",
            "icon ion-ios-americanfootball-outline",
            "icon ion-ios-baseball",
            "icon ion-ios-baseball-outline",
            "icon ion-ios-basketball",
            "icon ion-ios-basketball-outline",
            "icon ion-ios-tennisball",
            "icon ion-ios-tennisball-outline",
            "icon ion-ios-football",
            "icon ion-ios-football-outline",
            "icon ion-ios-body",
            "icon ion-ios-body-outline",
            "icon ion-ios-person",
            "icon ion-ios-person-outline",
            "icon ion-ios-personadd",
            "icon ion-ios-personadd-outline",
            "icon ion-ios-people",
            "icon ion-ios-people-outline",
            "icon ion-ios-musical-notes",
            "icon ion-ios-musical-note",
            "icon ion-ios-bell",
            "icon ion-ios-bell-outline",
            "icon ion-ios-mic",
            "icon ion-ios-mic-outline",
            "icon ion-ios-mic-off",
            "icon ion-ios-volume-high",
            "icon ion-ios-volume-low",
            "icon ion-ios-play",
            "icon ion-ios-play-outline",
            "icon ion-ios-pause",
            "icon ion-ios-pause-outline",
            "icon ion-ios-recording",
            "icon ion-ios-recording-outline",
            "icon ion-ios-fastforward",
            "icon ion-ios-fastforward-outline",
            "icon ion-ios-rewind",
            "icon ion-ios-rewind-outline",
            "icon ion-ios-skipbackward",
            "icon ion-ios-skipbackward-outline",
            "icon ion-ios-skipforward",
            "icon ion-ios-skipforward-outline",
            "icon ion-ios-shuffle-strong",
            "icon ion-ios-shuffle",
            "icon ion-ios-videocam",
            "icon ion-ios-videocam-outline",
            "icon ion-ios-film",
            "icon ion-ios-film-outline",
            "icon ion-ios-flask",
            "icon ion-ios-flask-outline",
            "icon ion-ios-lightbulb",
            "icon ion-ios-lightbulb-outline",
            "icon ion-ios-wineglass",
            "icon ion-ios-wineglass-outline",
            "icon ion-ios-pint",
            "icon ion-ios-pint-outline",
            "icon ion-ios-nutrition",
            "icon ion-ios-nutrition-outline",
            "icon ion-ios-flower",
            "icon ion-ios-flower-outline",
            "icon ion-ios-rose",
            "icon ion-ios-rose-outline",
            "icon ion-ios-paw",
            "icon ion-ios-paw-outline",
            "icon ion-ios-flame",
            "icon ion-ios-flame-outline",
            "icon ion-ios-sunny",
            "icon ion-ios-sunny-outline",
            "icon ion-ios-partlysunny",
            "icon ion-ios-partlysunny-outline",
            "icon ion-ios-cloudy",
            "icon ion-ios-cloudy-outline",
            "icon ion-ios-rainy",
            "icon ion-ios-rainy-outline",
            "icon ion-ios-thunderstorm",
            "icon ion-ios-thunderstorm-outline",
            "icon ion-ios-snowy",
            "icon ion-ios-moon",
            "icon ion-ios-moon-outline",
            "icon ion-ios-cloudy-night",
            "icon ion-ios-cloudy-night-outline",
            "icon ion-android-arrow-up",
            "icon ion-android-arrow-forward",
            "icon ion-android-arrow-down",
            "icon ion-android-arrow-back",
            "icon ion-android-arrow-dropup",
            "icon ion-android-arrow-dropup-circle",
            "icon ion-android-arrow-dropright",
            "icon ion-android-arrow-dropright-circle",
            "icon ion-android-arrow-dropdown",
            "icon ion-android-arrow-dropdown-circle",
            "icon ion-android-arrow-dropleft",
            "icon ion-android-arrow-dropleft-circle",
            "icon ion-android-add",
            "icon ion-android-add-circle",
            "icon ion-android-remove",
            "icon ion-android-remove-circle",
            "icon ion-android-close",
            "icon ion-android-cancel",
            "icon ion-android-radio-button-off",
            "icon ion-android-radio-button-on",
            "icon ion-android-checkmark-circle",
            "icon ion-android-checkbox-outline-blank",
            "icon ion-android-checkbox-outline",
            "icon ion-android-checkbox-blank",
            "icon ion-android-checkbox",
            "icon ion-android-done",
            "icon ion-android-done-all",
            "icon ion-android-menu",
            "icon ion-android-more-horizontal",
            "icon ion-android-more-vertical",
            "icon ion-android-refresh",
            "icon ion-android-sync",
            "icon ion-android-wifi",
            "icon ion-android-call",
            "icon ion-android-apps",
            "icon ion-android-settings",
            "icon ion-android-options",
            "icon ion-android-funnel",
            "icon ion-android-search",
            "icon ion-android-home",
            "icon ion-android-cloud-outline",
            "icon ion-android-cloud",
            "icon ion-android-download",
            "icon ion-android-upload",
            "icon ion-android-cloud-done",
            "icon ion-android-cloud-circle",
            "icon ion-android-favorite-outline",
            "icon ion-android-favorite",
            "icon ion-android-star-outline",
            "icon ion-android-star-half",
            "icon ion-android-star",
            "icon ion-android-calendar",
            "icon ion-android-alarm-clock",
            "icon ion-android-time",
            "icon ion-android-stopwatch",
            "icon ion-android-watch",
            "icon ion-android-locate",
            "icon ion-android-navigate",
            "icon ion-android-pin",
            "icon ion-android-compass",
            "icon ion-android-map",
            "icon ion-android-walk",
            "icon ion-android-bicycle",
            "icon ion-android-car",
            "icon ion-android-bus",
            "icon ion-android-subway",
            "icon ion-android-train",
            "icon ion-android-boat",
            "icon ion-android-plane",
            "icon ion-android-restaurant",
            "icon ion-android-bar",
            "icon ion-android-cart",
            "icon ion-android-camera",
            "icon ion-android-image",
            "icon ion-android-film",
            "icon ion-android-color-palette",
            "icon ion-android-create",
            "icon ion-android-mail",
            "icon ion-android-drafts",
            "icon ion-android-send",
            "icon ion-android-archive",
            "icon ion-android-delete",
            "icon ion-android-attach",
            "icon ion-android-share",
            "icon ion-android-share-alt",
            "icon ion-android-bookmark",
            "icon ion-android-document",
            "icon ion-android-clipboard",
            "icon ion-android-list",
            "icon ion-android-folder-open",
            "icon ion-android-folder",
            "icon ion-android-print",
            "icon ion-android-open",
            "icon ion-android-exit",
            "icon ion-android-contract",
            "icon ion-android-expand",
            "icon ion-android-globe",
            "icon ion-android-chat",
            "icon ion-android-textsms",
            "icon ion-android-hangout",
            "icon ion-android-happy",
            "icon ion-android-sad",
            "icon ion-android-person",
            "icon ion-android-people",
            "icon ion-android-person-add",
            "icon ion-android-contact",
            "icon ion-android-contacts",
            "icon ion-android-playstore",
            "icon ion-android-lock",
            "icon ion-android-unlock",
            "icon ion-android-microphone",
            "icon ion-android-microphone-off",
            "icon ion-android-notifications-none",
            "icon ion-android-notifications",
            "icon ion-android-notifications-off",
            "icon ion-android-volume-mute",
            "icon ion-android-volume-down",
            "icon ion-android-volume-up",
            "icon ion-android-volume-off",
            "icon ion-android-hand",
            "icon ion-android-desktop",
            "icon ion-android-laptop",
            "icon ion-android-phone-portrait",
            "icon ion-android-phone-landscape",
            "icon ion-android-bulb",
            "icon ion-android-sunny",
            "icon ion-android-alert",
            "icon ion-android-warning",
            "icon ion-social-twitter",
            "icon ion-social-twitter-outline",
            "icon ion-social-facebook",
            "icon ion-social-facebook-outline",
            "icon ion-social-googleplus",
            "icon ion-social-googleplus-outline",
            "icon ion-social-google",
            "icon ion-social-google-outline",
            "icon ion-social-dribbble",
            "icon ion-social-dribbble-outline",
            "icon ion-social-octocat",
            "icon ion-social-github",
            "icon ion-social-github-outline",
            "icon ion-social-instagram",
            "icon ion-social-instagram-outline",
            "icon ion-social-whatsapp",
            "icon ion-social-whatsapp-outline",
            "icon ion-social-snapchat",
            "icon ion-social-snapchat-outline",
            "icon ion-social-foursquare",
            "icon ion-social-foursquare-outline",
            "icon ion-social-pinterest",
            "icon ion-social-pinterest-outline",
            "icon ion-social-rss",
            "icon ion-social-rss-outline",
            "icon ion-social-tumblr",
            "icon ion-social-tumblr-outline",
            "icon ion-social-wordpress",
            "icon ion-social-wordpress-outline",
            "icon ion-social-reddit",
            "icon ion-social-reddit-outline",
            "icon ion-social-hackernews",
            "icon ion-social-hackernews-outline",
            "icon ion-social-designernews",
            "icon ion-social-designernews-outline",
            "icon ion-social-yahoo",
            "icon ion-social-yahoo-outline",
            "icon ion-social-buffer",
            "icon ion-social-buffer-outline",
            "icon ion-social-skype",
            "icon ion-social-skype-outline",
            "icon ion-social-linkedin",
            "icon ion-social-linkedin-outline",
            "icon ion-social-vimeo",
            "icon ion-social-vimeo-outline",
            "icon ion-social-twitch",
            "icon ion-social-twitch-outline",
            "icon ion-social-youtube",
            "icon ion-social-youtube-outline",
            "icon ion-social-dropbox",
            "icon ion-social-dropbox-outline",
            "icon ion-social-apple",
            "icon ion-social-apple-outline",
            "icon ion-social-android",
            "icon ion-social-android-outline",
            "icon ion-social-windows",
            "icon ion-social-windows-outline",
            "icon ion-social-html5",
            "icon ion-social-html5-outline",
            "icon ion-social-css3",
            "icon ion-social-css3-outline",
            "icon ion-social-javascript",
            "icon ion-social-javascript-outline",
            "icon ion-social-angular",
            "icon ion-social-angular-outline",
            "icon ion-social-nodejs",
            "icon ion-social-sass",
            "icon ion-social-python",
            "icon ion-social-chrome",
            "icon ion-social-chrome-outline",
            "icon ion-social-codepen",
            "icon ion-social-codepen-outline",
            "icon ion-social-markdown",
            "icon ion-social-tux",
            "icon ion-social-freebsd-devil",
            "icon ion-social-usd",
            "icon ion-social-usd-outline",
            "icon ion-social-bitcoin",
            "icon ion-social-bitcoin-outline",
            "icon ion-social-yen",
            "icon ion-social-yen-outline",
            "icon ion-social-euro",
            "icon ion-social-euro-outline",
        );

        return apply_filters('dental_care_ionicon_array', $ionicons);
    }

}
